title: "Nishith Singhai"
email: "singhai.nish@gmail.com"
description: "Senior Pipeline TD | Toolsmith | AI-VFX Explorer"
url: ""
baseurl: ""
twitter_username: singhaidotnish
github_username: singhaidotnish

theme: minimal-mistakes-jekyll

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

minimal_mistakes_skin: "default"

author:
  name: "Nishith Singhai"
  avatar: "/assets/images/avatar.png"
  bio: "Tool builder, creative technophile, and forever curious."

footer:
  links:
    - label: "Blog"
      icon: "fas fa-blog"
      url: "/blog/"

include:
  - _pages
  - _data

collections:
  resume:
    output: true