source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "minimal-mistakes-jekyll", "~> 4.24.0"
gem "faraday-retry"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-feed"
  gem "jekyll-include-cache"
end
